# Generated by Django 5.0.3 on 2024-03-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('capital', models.CharField(max_length=60, unique=True)),
                ('subregion', models.CharField(max_length=60)),
                ('region', models.CharField(max_length=60)),
                ('population', models.BigIntegerField()),
                ('area', models.BigIntegerField()),
                ('imezones', models.JSONField()),
                ('borders', models.JSONField()),
                ('numericCode', models.CharField(max_length=60, unique=True)),
                ('flag', models.CharField(max_length=60, unique=True)),
            ],
        ),
    ]
